// Package golden owns the parity-harness corpus for the bash↔Go
// render comparison.
//
// The byte-equality contract: for each of the 36 matrix cells,
// pkg/render.Render(bundle, env) MUST produce JSON identical to the
// committed expected/<cell>/{sing-box,xray}.json.
//
// Goldens are generated by piping bash render-config's output through
// `jq -S --indent 2` (sorted keys, 2-space indent, trailing newline);
// pkg/render emits the same shape via stdlib `encoding/json` with
// `SetIndent` + `SetEscapeHTML(false)`. The encoders agree on every
// formatting choice that matters.
//
// Cells:
//
//	proto-{all,tcp-vision,xhttp}_ts-{on,off}_corp-{on,off}_n{1,2,3}
//
// 3*2*2*3 = 36 cells. tcp-vision drops xray (12 cells xray-less),
// so 36 sing-box files + 24 xray files = 60 total.
//
// Regenerate (after an intentional render-config change):
//
//	bash internal/tests/golden/scripts/generate.sh
//
// The goldens encode bash render-config's current behavior including
// any latent bugs. Divergence is a parity break, NOT a bug fix.
package golden

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"bb-dpi/client/bb-vpn/pkg/bundle"
	"bb-dpi/client/bb-vpn/pkg/render"
)

const (
	expectedDir  = "expected"
	skeletonsDir = "skeletons"
	inputsDir    = "inputs"
	// Matrix is proto{3} * ts{2} * corp{2} * n{3} = 36 cells; each has
	// sing-box.json, and only non-tcp-vision (24 cells) also has
	// xray.json. So total .json files = 36 + 24 = 60.
	totalCells       = 36
	totalGoldenFiles = 60
	tcpVisionPrefix  = "proto-tcp-vision"
)

// Cell describes a single matrix combination plus its file-presence rule.
type Cell struct {
	Name          string
	Proto         string
	WithTailscale bool
	WithCorpDNS   bool
	ServerCount   int
}

func (c Cell) HasXray() bool { return c.Proto != "tcp-vision" }

// allCells enumerates the full matrix in the same iteration order as
// generate.sh (proto outer, ts, corp, n inner).
func allCells() []Cell {
	var cells []Cell
	for _, proto := range []string{"all", "tcp-vision", "xhttp"} {
		for _, ts := range []string{"off", "on"} {
			for _, corp := range []string{"off", "on"} {
				for _, n := range []int{1, 2, 3} {
					cells = append(cells, Cell{
						Name:          "proto-" + proto + "_ts-" + ts + "_corp-" + corp + "_n" + strconv.Itoa(n),
						Proto:         proto,
						WithTailscale: ts == "on",
						WithCorpDNS:   corp == "on",
						ServerCount:   n,
					})
				}
			}
		}
	}
	return cells
}

func TestGolden_CellDirectoriesExist(t *testing.T) {
	for _, c := range allCells() {
		dir := filepath.Join(expectedDir, c.Name)
		info, err := os.Stat(dir)
		if err != nil {
			t.Errorf("cell %q: %v", c.Name, err)
			continue
		}
		if !info.IsDir() {
			t.Errorf("cell %q: not a directory", c.Name)
		}
	}

	// No surprise cells either. Filter for directories so stray files
	// (.DS_Store, swap files) don't inflate the count; name offenders
	// in the error so drift is diagnosable.
	entries, err := os.ReadDir(expectedDir)
	if err != nil {
		t.Fatalf("read %s: %v", expectedDir, err)
	}
	var dirCount int
	var nonDirs []string
	for _, e := range entries {
		if e.IsDir() {
			dirCount++
		} else {
			nonDirs = append(nonDirs, e.Name())
		}
	}
	if dirCount != totalCells {
		t.Errorf("cell count = %d, want %d (non-dir entries: %v)", dirCount, totalCells, nonDirs)
	}
}

func TestGolden_PerCellFilesPresentAndValid(t *testing.T) {
	for _, c := range allCells() {
		t.Run(c.Name, func(t *testing.T) {
			singBoxPath := filepath.Join(expectedDir, c.Name, "sing-box.json")
			mustBeValidJSON(t, singBoxPath)

			xrayPath := filepath.Join(expectedDir, c.Name, "xray.json")
			_, err := os.Stat(xrayPath)
			switch {
			case !c.HasXray() && err == nil:
				t.Errorf("%s: xray.json must NOT exist for tcp-vision cells", xrayPath)
			case c.HasXray() && os.IsNotExist(err):
				t.Errorf("%s: xray.json required for non-tcp-vision cells", xrayPath)
			case c.HasXray() && err == nil:
				mustBeValidJSON(t, xrayPath)
			case err != nil && !os.IsNotExist(err):
				t.Errorf("%s: stat: %v", xrayPath, err)
			}
		})
	}
}

func TestGolden_TotalFileCount(t *testing.T) {
	var count int
	err := filepath.Walk(expectedDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && strings.HasSuffix(path, ".json") {
			count++
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk: %v", err)
	}
	if count != totalGoldenFiles {
		t.Errorf("total .json files = %d, want %d", count, totalGoldenFiles)
	}
}

// TestParity_ByteEqual is the Phase 2 merge gate: pkg/render must
// produce bytes identical to the committed goldens for every cell in
// the matrix. Goldens are jq -S --indent 2 canonicalized so stdlib
// encoding/json matches by construction.
func TestParity_ByteEqual(t *testing.T) {
	skel, err := loadSkeletons()
	if err != nil {
		t.Fatalf("load skeletons: %v", err)
	}
	serversByCount := loadServersByCount(t)
	env := goldenEnv()

	for _, c := range allCells() {
		t.Run(c.Name, func(t *testing.T) {
			b := &bundle.Bundle{
				SchemaVersion: 1,
				IssuedAt:      "2026-05-19T00:00:00Z",
				MinVersions: bundle.MinVersions{
					BBVPN: "1.0.0", SingBox: "1.13.0", Xray: "25.12.8",
				},
				Servers:   serversByCount[c.ServerCount],
				Skeletons: skel,
				Render: bundle.Render{
					Proto:         c.Proto,
					WithTailscale: c.WithTailscale,
					WithCorpDNS:   c.WithCorpDNS,
				},
			}
			gotSB, gotXray, err := render.Render(b, env)
			if err != nil {
				t.Fatalf("Render: %v", err)
			}

			wantSB, err := os.ReadFile(filepath.Join(expectedDir, c.Name, "sing-box.json"))
			if err != nil {
				t.Fatalf("read sing-box golden: %v", err)
			}
			if !bytes.Equal(gotSB, wantSB) {
				t.Errorf("sing-box.json bytes differ at byte %d", firstDiffPos(gotSB, wantSB))
				logDiffContext(t, "want", wantSB, gotSB)
				logDiffContext(t, "got ", gotSB, wantSB)
			}

			if c.HasXray() {
				wantXray, err := os.ReadFile(filepath.Join(expectedDir, c.Name, "xray.json"))
				if err != nil {
					t.Fatalf("read xray golden: %v", err)
				}
				if !bytes.Equal(gotXray, wantXray) {
					t.Errorf("xray.json bytes differ at byte %d", firstDiffPos(gotXray, wantXray))
					logDiffContext(t, "want", wantXray, gotXray)
					logDiffContext(t, "got ", gotXray, wantXray)
				}
			} else if len(gotXray) != 0 {
				t.Errorf("xray output must be empty for tcp-vision, got %d bytes", len(gotXray))
			}
		})
	}
}

func loadSkeletons() (bundle.Skeletons, error) {
	sb, err := os.ReadFile(filepath.Join(skeletonsDir, "sing-box-skeleton.json"))
	if err != nil {
		return bundle.Skeletons{}, err
	}
	xr, err := os.ReadFile(filepath.Join(skeletonsDir, "xray-xhttp-skeleton.json"))
	if err != nil {
		return bundle.Skeletons{}, err
	}
	return bundle.Skeletons{
		SingBox:   json.RawMessage(sb),
		XrayXHTTP: json.RawMessage(xr),
	}, nil
}

func loadServersByCount(t *testing.T) map[int][]bundle.Server {
	t.Helper()
	out := make(map[int][]bundle.Server, 3)
	for _, n := range []int{1, 2, 3} {
		data, err := os.ReadFile(filepath.Join(inputsDir, "servers-"+strconv.Itoa(n)+".json"))
		if err != nil {
			t.Fatalf("load servers-%d: %v", n, err)
		}
		var srvs []bundle.Server
		if err := json.Unmarshal(data, &srvs); err != nil {
			t.Fatalf("parse servers-%d: %v", n, err)
		}
		out[n] = srvs
	}
	return out
}

// goldenEnv mirrors inputs/env.sh — the deterministic env used to
// generate the bash goldens.
func goldenEnv() render.Env {
	return render.Env{
		HOME:              "/Users/example",
		UUID:              "00000000-0000-0000-0000-000000000000",
		TailscaleAuthKey:  "auth-key-deterministic-fake-test",
		TailscaleHostname: "test-host",
		InternalDNS1:      "10.0.0.53",
		CompanyDomain:     "example.invalid",
		Flow:              "xtls-rprx-vision",
		Fingerprint:       "chrome",
	}
}

func mustBeValidJSON(t *testing.T, path string) {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Errorf("%s: %v", path, err)
		return
	}
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		t.Errorf("%s: invalid JSON: %v", path, err)
		return
	}
	if _, ok := v.(map[string]any); !ok {
		t.Errorf("%s: top-level must be a JSON object, got %T", path, v)
	}
}

func firstDiffPos(a, b []byte) int {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	for i := 0; i < n; i++ {
		if a[i] != b[i] {
			return i
		}
	}
	return n // one side is a prefix of the other
}

func logDiffContext(t *testing.T, label string, data, other []byte) {
	t.Helper()
	pos := firstDiffPos(data, other)
	start := pos - 80
	if start < 0 {
		start = 0
	}
	end := pos + 80
	if end > len(data) {
		end = len(data)
	}
	t.Logf("%s[byte %d..]\n%s", label, pos, string(data[start:end]))
}
